# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         RunApp
version:      0.12
version_from: lib/RunApp.pm
installdirs:  site
requires:
    App::Control:                  0
    Template:                      0
    YAML:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.25_10
