distribution_type: module
generated_by: Module::Install version 0.64
license: unknown
name: RunApp
no_index: 
  directory: 
    - inc
    - t
requires: 
  App::Control: 0
  Template: 0
  YAML: 0
version: 0.13
